version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/product_delivery_service
      - SPRING_DATASOURCE_USERNAME=pds_user
      - SPRING_DATASOURCE_PASSWORD=pdpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - "8080:8080"

  db:
    image: 'postgres:14.5-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=pds_user
      - POSTGRES_PASSWORD=pdpass
      - POSTGRES_DB=product_delivery_service
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql
